### PR TITLE
WIP: BCSO implementation

### LINKED ISSUE #14: Add Binary Cat-Swam-Optimizer
Implementation should follow "Sharafi Y.,Khanesar M.A., Teshnehlab M.: _Discrete Binary Cat Swarm Optimization Algorithm_"

### PR DESCRIPTION
**Pull request by ptrc-n**
Basic implementation of BCSO is done.
Binary versions of `moving.move` and `moving.alter_position` will follow tomorrow.
Intends to resolve #14 .

### CODE REVIEW

**Comment by ptrc-n** [comment]
An example notebook should still be added, but afterwards we should be good to go

**Comment by carlassmann** [comment]
Can you combine the two CSO classes and consider the changes I have made in the dev branch regarding the counting of function calls etc?

You could also add an example with an arbitrary large knapsack problem. I believe the larger the problem, the better CSO will perform compared to other algorithms. You could compare Simulated Annealing with BCSO and Genetic Algorithm for similar runtimes :) I would be really excited to see the results!

**Comment by ptrc-n** [comment]
Will have a look at it in the next few days ...

I am not quiet sure about adding more examples for the algorithms which are already implemented. 
We might want to keep those as tightly arranged as possible.

**Comment by carlassmann** [comment]
I would not generate a new class for each optimizer result. Especially if the new class does not hold anything additional. I like the way you solved the double implementation of the CSO with the BCSO but there still is some rome for refactoring. I will do that :) should just take a few minutes

**Comment by carlassmann** [comment]
I removed the CSO-specific result classes and changed the docstrings to be consistent to the other algorithms :) And I made the jupyter notebook work with the recent changes.

I guess now its ready to go

**Pull request merged**
